# name: gh-pages-deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.3.1

#       - name: Cache pnpm modules
#         uses: actions/cache@v2
#         with:
#           path: ~/.pnpm-store
#           key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-

#       - uses: pnpm/action-setup@v2.1.0
#         with:
#           version: 6.0.2
#           run_install: true

#       - name: Build
#         run: pnpm build:gh-pages

#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@4.1.3
#         with:
#           branch: gh-pages
#           folder: build
